<?php

namespace Wa\BackBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    //AFFICHER NB CATEGORIE ACTIVE
    public function nbCategorieActive(){
        $query= $this->createQueryBuilder("cat")
            ->addGroupBy('cat.active')
            ->getQuery();
        die(dump($query->getResult()));

        return $query->getResult();

    }
    //AFFICHER NB ACTIF ET INACTIF
    public function nbCategorieActifInactif(){
        $query= $this->createQueryBuilder("cat")
            ->addGroupBy('cat.active')
            ->andHaving('cat.active=1')
            ->orWhere('cat.active=0')
            ->getQuery();
        die(dump($query->getResult()));

        return $query->getResult();
    }
    //AFFICHER CATEGORIE POSITION > 2
    public function categoriesParPosition($position){
        $query= $this->createQueryBuilder("cat")
            ->where('cat.position > positionCat')
            ->setParameter("positionCat",$position)
            ->getQuery();
        die(dump($query->getResult()));

        return $query->getResult();
    }

    public function buildCategorieOrderPosition(){
        $queryBuilder = $this->createQueryBuilder("cat")
                 ->orderBy("cat.position");

        return $queryBuilder;
    }
}
