<?php

namespace Wa\BackBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    //AFFICHER LES COMMENTAIRES D'UN PRODUIT
    public function commentByPdt($id){
        $query= $this->createQueryBuilder("comment")
            ->where('comment.produit = :id')
            ->setParameter('id', $id)
            ->getQuery();

        //die(dump($query->getResult()));
        return $query->getResult();
    }

}
