<?php

namespace Wa\BackBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
    //AFFICHER GROUPE ORDER BY NAME
    public function listGroupeOrderName(){
        $queryBuilder= $this->createQueryBuilder("grp")
            ->orderBy("grp.name");

        return $queryBuilder;
    }
}
