<?php

namespace Wa\BackBundle\Repository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository
{
    //AFFICHER LISTE MARQUE
    public function afficherMarques(){
        $query= $this->createQueryBuilder("marque")
            ->getQuery();

        return $query;
    }
}
