<?php

namespace Wa\BackBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{

    //AFFICHER TAG PAR ORDRE ASC
    public function findAllTagsOrder(){
        $queryBuilder = $this->createQueryBuilder("tag")
            ->orderBy("tag.nom");

        return $queryBuilder;
    }
}
