wa_back_categorie_show:
    path: /categorie/show/{id}
    defaults: { _controller: WaBackBundle:Categorie:show }
    requirements:
        id: \d+

wa_back_categorie_creation:
    path: /categorie/create
    defaults: { _controller: WaBackBundle:Categorie:create}

wa_back_categorie:
    path: /categorie
    defaults: { _controller: WaBackBundle:Categorie:index}

wa_back_categorie_update:
    path: /categorie/update/{id}
    defaults: { _controller: WaBackBundle:Categorie:update }

wa_back_categorie_delete:
    path: /categorie/delete/{id}
    defaults: { _controller: WaBackBundle:Categorie:delete }